import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'



const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {


  return (
    <>
    {/* <style jsx>
      {`
      .myimg{
        border-radius:15px
      }
      `}
    </style> */}
      <Head>
        <title>Coder Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        

    <Image className={styles.myimg} src="/home.jpg" width={200} height={200} alt="no image found"></Image>

    <h1 className={styles.head}><span className='mySpan'>{`<Coder Blog/>`
}</span></h1>
        <p className={styles.description}>A blog site for coders Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum atque incidunt fugiat quisquam nemo, velit reiciendis ea ipsum iure voluptate pariatur nostrum corporis vero consectetur voluptatibus nesciunt provident assumenda. Est dolorum sequi quidem accusamus?</p>
      
        <h2 className={styles.h2}>Latest Blogs</h2>

        
        <div className={styles.blogs}>
        {props.allBlogs.map(blog=>{
          return (
       
            <div className="blogItems" key={blog.slug}>
              <h1>{blog.title}</h1>
              <p>{blog.metadesc} </p>
              <Link href={`/blogpost/${blog.slug}`}>
              <button className={styles.btn}>Read More</button></Link>
  
            </div>
          )
        })}
         
          </div>
      </main>
    </>


  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  
  let data= await fetch('http://localhost:3000/api/getlatestblogs')
  let allBlogs=await data.json()
  // Pass data to the page via props
  return { props: {allBlogs}}
}
